
remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-titles-from-headings

title: "DigiHealth Blog"

description: "GBAC Blog - By Karim Haidar"

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true 
